# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Milagros\Desktop\ProyectoDeSoftware\login_correcto.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(494, 325)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(30)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.994318 rgba(156, 92, 196, 252));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-110, 30, 621, 131))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnSiguiente = QtWidgets.QPushButton(self.centralwidget)
        self.btnSiguiente.setGeometry(QtCore.QRect(100, 170, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(16)
        self.btnSiguiente.setFont(font)
        self.btnSiguiente.setStyleSheet("background-color: rgb(170, 0, 255);\n"
"border-radius:20px;\n"
"color:white;")
        self.btnSiguiente.setObjectName("btnSiguiente")
        self.btnSalir = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalir.setGeometry(QtCore.QRect(270, 270, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(16)
        self.btnSalir.setFont(font)
        self.btnSalir.setStyleSheet("background-color: rgb(170, 0, 255);\n"
"border-radius:20px;\n"
"color:white;")
        self.btnSalir.setObjectName("btnSalir")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Ha ingresado </p><p align=\"center\">correctamente !</p></body></html>"))
        self.btnSiguiente.setText(_translate("MainWindow", "Siguiente"))
        self.btnSalir.setText(_translate("MainWindow", "Salir"))
