# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Milagros\Desktop\ProyectoDeSoftware\Menu_limlife.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(652, 484)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 1))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_superior = QtWidgets.QFrame(self.frame_3)
        self.frame_superior.setGeometry(QtCore.QRect(-30, 0, 671, 51))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 16777214))
        self.frame_superior.setStyleSheet("\n"
"QFrame{\n"
"background-color:rgb(0,0,0);\n"
"}\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(53,53,79);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.btnMinimizar = QtWidgets.QPushButton(self.frame_superior)
        self.btnMinimizar.setGeometry(QtCore.QRect(570, 10, 31, 23))
        self.btnMinimizar.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(255, 255, 255, 252));")
        self.btnMinimizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Milagros\\Desktop\\ProyectoDeSoftware\\../Menu Lateral desplegable/minimizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMinimizar.setIcon(icon)
        self.btnMinimizar.setIconSize(QtCore.QSize(40, 40))
        self.btnMinimizar.setObjectName("btnMinimizar")
        self.btnCerrar = QtWidgets.QPushButton(self.frame_superior)
        self.btnCerrar.setGeometry(QtCore.QRect(610, 10, 31, 21))
        self.btnCerrar.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(255, 255, 255, 252));")
        self.btnCerrar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Milagros\\Desktop\\ProyectoDeSoftware\\images_food/cerrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCerrar.setIcon(icon1)
        self.btnCerrar.setIconSize(QtCore.QSize(45, 45))
        self.btnCerrar.setObjectName("btnCerrar")
        self.pushButton = QtWidgets.QPushButton(self.frame_superior)
        self.pushButton.setGeometry(QtCore.QRect(30, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color:rgb(20,200,220);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_superior)
        self.pushButton_7.setGeometry(QtCore.QRect(290, 10, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("color:rgb(20,200,220);\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setGeometry(QtCore.QRect(0, 50, 231, 401))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(16)
        self.frame_2.setFont(font)
        self.frame_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.frame_2.setStyleSheet("QFrame{\n"
"background-color:rgb(53,53,79);\n"
"}\n"
"QPushButton{\n"
"background-color:#000000ff;\n"
"color:rgb(20,20,220);\n"
"border-radius:10px;\n"
"border:1px solid white;\n"
"}\n"
"QPushbutton:hover{\n"
"background-color:black;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btnPlatillo = QtWidgets.QPushButton(self.frame_2)
        self.btnPlatillo.setGeometry(QtCore.QRect(10, 40, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(16)
        self.btnPlatillo.setFont(font)
        self.btnPlatillo.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btnPlatillo.setStyleSheet("color:rgb(20,200,220);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\Milagros\\Desktop\\ProyectoDeSoftware\\../../Downloads/3558101_cook_dish_food_menu_rice_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlatillo.setIcon(icon2)
        self.btnPlatillo.setIconSize(QtCore.QSize(30, 36))
        self.btnPlatillo.setObjectName("btnPlatillo")
        self.btnPedido = QtWidgets.QPushButton(self.frame_2)
        self.btnPedido.setGeometry(QtCore.QRect(10, 110, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(16)
        self.btnPedido.setFont(font)
        self.btnPedido.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btnPedido.setStyleSheet("color:rgb(20,200,220);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\Milagros\\Desktop\\ProyectoDeSoftware\\images_food/pedidos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPedido.setIcon(icon3)
        self.btnPedido.setIconSize(QtCore.QSize(47, 30))
        self.btnPedido.setObjectName("btnPedido")
        self.btnNosotros = QtWidgets.QPushButton(self.frame_2)
        self.btnNosotros.setGeometry(QtCore.QRect(10, 180, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(16)
        self.btnNosotros.setFont(font)
        self.btnNosotros.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btnNosotros.setStyleSheet("color:rgb(20,200,220);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\Milagros\\Desktop\\ProyectoDeSoftware\\images_food/nostros.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNosotros.setIcon(icon4)
        self.btnNosotros.setIconSize(QtCore.QSize(33, 30))
        self.btnNosotros.setObjectName("btnNosotros")
        self.btnSalir = QtWidgets.QPushButton(self.frame_2)
        self.btnSalir.setGeometry(QtCore.QRect(10, 250, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(16)
        self.btnSalir.setFont(font)
        self.btnSalir.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btnSalir.setAutoFillBackground(False)
        self.btnSalir.setStyleSheet("color:rgb(20,200,220);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("c:\\Users\\Milagros\\Desktop\\ProyectoDeSoftware\\images_food/salir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalir.setIcon(icon5)
        self.btnSalir.setIconSize(QtCore.QSize(26, 30))
        self.btnSalir.setObjectName("btnSalir")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(150, 40, 481, 451))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(80, 10, 411, 401))
        self.label.setStyleSheet("border:10px solid white;\n"
"")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\Milagros\\Desktop\\ProyectoDeSoftware\\../123.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(90, 20, 401, 391))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("c:\\Users\\Milagros\\Desktop\\ProyectoDeSoftware\\images_food/123.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.frame_4.raise_()
        self.frame_superior.raise_()
        self.frame_2.raise_()
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Menu "))
        self.pushButton_7.setText(_translate("MainWindow", "RESTAURANT \"LIMLIFE\""))
        self.btnPlatillo.setText(_translate("MainWindow", "       Platillos"))
        self.btnPedido.setText(_translate("MainWindow", "       Pedidos"))
        self.btnNosotros.setText(_translate("MainWindow", "       Nosotros"))
        self.btnSalir.setText(_translate("MainWindow", "       Salir"))
