# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Milagros\Desktop\ProyectoDeSoftware\Pedidos.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(664, 466)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(203, 248, 236, 252));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(150, 70, 331, 201))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.lblCodigo = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblCodigo.setFont(font)
        self.lblCodigo.setStyleSheet("color:black;\n"
"")
        self.lblCodigo.setObjectName("lblCodigo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblCodigo)
        self.txtNombre = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        self.txtNombre.setFont(font)
        self.txtNombre.setAutoFillBackground(False)
        self.txtNombre.setStyleSheet("border-radius:5px;\n"
"border:1px solid black;\n"
"color:black;\n"
"\n"
"font: 12pt \"Mongolian Baiti\";")
        self.txtNombre.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.txtNombre.setClearButtonEnabled(True)
        self.txtNombre.setObjectName("txtNombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtNombre)
        self.lblTitulo = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setStyleSheet("color:black;")
        self.lblTitulo.setObjectName("lblTitulo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblTitulo)
        self.txtPlatillo = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        self.txtPlatillo.setFont(font)
        self.txtPlatillo.setStyleSheet("border-radius:5px;\n"
"border:1px solid black;\n"
"color:black;\n"
"font: 12pt \"Mongolian Baiti\";")
        self.txtPlatillo.setClearButtonEnabled(True)
        self.txtPlatillo.setObjectName("txtPlatillo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtPlatillo)
        self.lblCategoria = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblCategoria.setFont(font)
        self.lblCategoria.setStyleSheet("color:black;")
        self.lblCategoria.setObjectName("lblCategoria")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblCategoria)
        self.comboSede = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboSede.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        self.comboSede.setFont(font)
        self.comboSede.setStyleSheet("color:black;\n"
"font: 12pt \"Mongolian Baiti\";")
        self.comboSede.setObjectName("comboSede")
        self.comboSede.addItem("")
        self.comboSede.addItem("")
        self.comboSede.addItem("")
        self.comboSede.addItem("")
        self.comboSede.addItem("")
        self.comboSede.addItem("")
        self.comboSede.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboSede)
        self.lblAutor = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblAutor.setFont(font)
        self.lblAutor.setStyleSheet("color:black;")
        self.lblAutor.setObjectName("lblAutor")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblAutor)
        self.txtDireccion = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        self.txtDireccion.setFont(font)
        self.txtDireccion.setStyleSheet("border-radius:5px;\n"
"border:1px solid black;\n"
"color:black;\n"
"font: 12pt \"Mongolian Baiti\";")
        self.txtDireccion.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.txtDireccion.setClearButtonEnabled(True)
        self.txtDireccion.setObjectName("txtDireccion")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtDireccion)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnRegistrar = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnRegistrar.setFont(font)
        self.btnRegistrar.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(161, 161, 236, 255));\n"
"border-radius:7px;\n"
"color:white;\n"
"border:1px solid black;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(53,53,79);\n"
"border-radius:10px;\n"
"}")
        self.btnRegistrar.setObjectName("btnRegistrar")
        self.horizontalLayout.addWidget(self.btnRegistrar)
        self.btnLimpiar = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnLimpiar.setFont(font)
        self.btnLimpiar.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(161, 161, 236, 255));\n"
"border-radius:7px;\n"
"color:white;\n"
"border:1px solid black;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(53,53,79);\n"
"border-radius:10px;\n"
"}")
        self.btnLimpiar.setObjectName("btnLimpiar")
        self.horizontalLayout.addWidget(self.btnLimpiar)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 20, 601, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setStyleSheet("color:black;")
        self.label.setObjectName("label")
        self.tblSalida = QtWidgets.QTableWidget(self.centralwidget)
        self.tblSalida.setGeometry(QtCore.QRect(110, 240, 401, 211))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tblSalida.setFont(font)
        self.tblSalida.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(161, 161, 236, 255));\n"
"color:black;\n"
"font: 12pt \"Mongolian Baiti\";")
        self.tblSalida.setObjectName("tblSalida")
        self.tblSalida.setColumnCount(4)
        self.tblSalida.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblSalida.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSalida.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSalida.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSalida.setHorizontalHeaderItem(3, item)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblCodigo.setText(_translate("MainWindow", "Nombre:"))
        self.txtNombre.setPlaceholderText(_translate("MainWindow", "Nombre", "Codigo"))
        self.lblTitulo.setText(_translate("MainWindow", "Platillo:"))
        self.txtPlatillo.setPlaceholderText(_translate("MainWindow", "Escriba su Platillo"))
        self.lblCategoria.setText(_translate("MainWindow", "Sede:"))
        self.comboSede.setItemText(0, _translate("MainWindow", "Seleccione..."))
        self.comboSede.setItemText(1, _translate("MainWindow", "Ate"))
        self.comboSede.setItemText(2, _translate("MainWindow", "SantaAnita"))
        self.comboSede.setItemText(3, _translate("MainWindow", "Lima"))
        self.comboSede.setItemText(4, _translate("MainWindow", "Chosica"))
        self.comboSede.setItemText(5, _translate("MainWindow", "LaVictoria"))
        self.comboSede.setItemText(6, _translate("MainWindow", "Narnia"))
        self.lblAutor.setText(_translate("MainWindow", "Dirección:"))
        self.txtDireccion.setPlaceholderText(_translate("MainWindow", "Punto de Referencia", "Autor"))
        self.btnRegistrar.setText(_translate("MainWindow", "REGISTRAR"))
        self.btnLimpiar.setText(_translate("MainWindow", "LIMPIAR"))
        self.label.setText(_translate("MainWindow", "Registre su Pedido, Por favor !"))
        item = self.tblSalida.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NOMBRE"))
        item = self.tblSalida.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PLATILLO"))
        item = self.tblSalida.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SEDE"))
        item = self.tblSalida.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "DIRECCION"))
