# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Milagros\Desktop\ProyectoDeSoftware\platillos.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(671, 411)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(30)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(110, 214, 188, 252));\n"
"\n"
"")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(16)
        self.centralwidget.setFont(font)
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.centralwidget.setObjectName("centralwidget")
        self.comboPlatillo = QtWidgets.QComboBox(self.centralwidget)
        self.comboPlatillo.setGeometry(QtCore.QRect(60, 160, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(16)
        self.comboPlatillo.setFont(font)
        self.comboPlatillo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboPlatillo.setStyleSheet("QComboBox{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(161, 161, 236, 255));\n"
"border-radius:20px;\n"
"color:white;\n"
"border:2px solid white;\n"
"}\n"
"QComboBox:hover{\n"
"background-color:rgb(53,53,79);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.comboPlatillo.setObjectName("comboPlatillo")
        self.comboPlatillo.addItem("")
        self.comboPlatillo.addItem("")
        self.comboPlatillo.addItem("")
        self.comboPlatillo.addItem("")
        self.comboPlatillo.addItem("")
        self.comboPlatillo.addItem("")
        self.comboPlatillo.addItem("")
        self.comboPlatillo.addItem("")
        self.comboPlatillo.addItem("")
        self.comboPlatillo.addItem("")
        self.comboPrecio = QtWidgets.QComboBox(self.centralwidget)
        self.comboPrecio.setEnabled(True)
        self.comboPrecio.setGeometry(QtCore.QRect(360, 150, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(16)
        self.comboPrecio.setFont(font)
        self.comboPrecio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboPrecio.setStyleSheet("QComboBox{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(161, 161, 236, 255));\n"
"border-radius:20px;\n"
"color:white;\n"
"border:2px solid white;\n"
"}\n"
"QComboBox:hover{\n"
"background-color:rgb(53,53,79);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.comboPrecio.setObjectName("comboPrecio")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-40, 0, 671, 111))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:Black;\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 110, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:Black;\n"
"")
        self.label_3.setObjectName("label_3")
        self.btnVer = QtWidgets.QPushButton(self.centralwidget)
        self.btnVer.setGeometry(QtCore.QRect(240, 310, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(16)
        self.btnVer.setFont(font)
        self.btnVer.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(161, 161, 236, 255));\n"
"border-radius:10px;\n"
"color:white;\n"
"border:2px solid white;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(53,53,79);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.btnVer.setObjectName("btnVer")
        self.lblPrecio = QtWidgets.QLabel(self.centralwidget)
        self.lblPrecio.setGeometry(QtCore.QRect(10, 230, 651, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(14)
        self.lblPrecio.setFont(font)
        self.lblPrecio.setStyleSheet("color:black;\n"
"")
        self.lblPrecio.setObjectName("lblPrecio")
        self.btnBack = QtWidgets.QPushButton(self.centralwidget)
        self.btnBack.setGeometry(QtCore.QRect(30, 330, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(18)
        self.btnBack.setFont(font)
        self.btnBack.setStyleSheet("QPushButton{\n"
"background-color: rgb(170, 170, 255);\n"
"border-radius:10px;\n"
"border:3px solid black;\n"
"color:black;\n"
"\n"
"}\n"
"QPushbutton:hover{\n"
"background-color:white;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.btnBack.setObjectName("btnBack")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboPlatillo.setItemText(0, _translate("MainWindow", "Seleccione"))
        self.comboPlatillo.setItemText(1, _translate("MainWindow", "Lomo Saltado"))
        self.comboPlatillo.setItemText(2, _translate("MainWindow", "Ceviche"))
        self.comboPlatillo.setItemText(3, _translate("MainWindow", "Ají de Gallina"))
        self.comboPlatillo.setItemText(4, _translate("MainWindow", "Causa Limeña"))
        self.comboPlatillo.setItemText(5, _translate("MainWindow", "Pachamanca"))
        self.comboPlatillo.setItemText(6, _translate("MainWindow", "Arroz con Pollo"))
        self.comboPlatillo.setItemText(7, _translate("MainWindow", "Tallarines a la Huancaina"))
        self.comboPlatillo.setItemText(8, _translate("MainWindow", "Aguadito"))
        self.comboPlatillo.setItemText(9, _translate("MainWindow", "Carapulcra"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Seleccione !, Que tipo de </p><p align=\"center\">platillo Quiere...</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Platillos:"))
        self.label_3.setText(_translate("MainWindow", "Precios:"))
        self.btnVer.setText(_translate("MainWindow", "Ver Precio.."))
        self.lblPrecio.setText(_translate("MainWindow", "El Precio del Platillo es:"))
        self.btnBack.setText(_translate("MainWindow", "BACK"))
